FROM node:12 AS builder

WORKDIR /app

# COPY package.json .
# COPY yarn.lock .

# COPY frontend ./frontend
# COPY backend ./backend


# RUN yarn install --pure-lockfile --non-interactive

# WORKDIR /app/backend

# CMD ["nodemon"]

#FROM nginx:stable

#WORKDIR /var/www

#COPY --from=builder /app/frontend/build /var/www/

#COPY ./nginx.conf /etc/nginx/conf.d/default.conf



# EXPOSE 80

